server:
  port: 8090

spring:
  application:
    name: ChatGPT

app:
  config:
    client:
      openai:
        url: "https://api.openai.com/v1"
        api-key: "XXXXXXX"
        model: "text-davinci-002"
        max-token: 300
        temperature: 0.7
        top-p: 1.0
